docs/team/myc37.md
docs/team/raynerljm.md

- Added empty skeletal PPP for myc37
- Helped update code contribution link for raynerljm

Add skeletal PPP for myc37

---

docs/UserGuide.md

- Updated UG boilerplate from AB3 to suit onlyFAs
- Need each team member to add their part of the UG 
- Table of contents will be filled in thereafter

Add boilerplate for UG

---

docs/UserGuide.md

Add features and commands to user guide

---

docs/UserGuide.md

Example in summary was incorrect for view meeting and delete meeting, fixed

Fix summary errors

---

docs/team/joelwongjy.md

Add skeletal ppp for joelwongjy

---

docs/team/sheimoria.md

Add skeletal ppp for sheimoria

---

docs/UserGuide.md

Add table of contents to user guide

---

README.md

Link CI banner to project

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/meeting/Meeting.java
src/main/java/seedu/address/model/meeting/NonOverlappingMeetingList.java
src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
src/main/java/seedu/address/model/meeting/exceptions/MeetingNotFoundException.java
src/main/java/seedu/address/model/meeting/exceptions/OverlappingMeetingsException.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java

Issue #12: As a first time user I can schedule meetings with clients

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/DateTime.java
src/main/java/seedu/address/model/person/Person.java
src/main/resources/view/DarkTheme.css

13 last contacted

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/Extensions.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/MeetingListPanel.fxml

Closes #60.
1. Add right panel. Current only used for displaying meetings.
2. Improve color scheme and layout.
Will be extended in future to display client information.

Issue #60: Add side panel to display more information

---

src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
src/main/java/seedu/address/model/policy/Policy.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/storage/JsonAdaptedPolicy.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Issue#59 save policy

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/policy/ViewPolicyCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/policy/ViewPolicyCommandParser.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/policy/Policy.java

- Added ViewPolicyCommand and parser
- Added new method to Person to display policy set as a pretty string
- Added new method to Policy to display all details as a pretty string

Add functionality for  ViewPolicy command

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Date.java
src/main/java/seedu/address/model/person/DateTime.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java

Closes #64 
1. Save `birthday` and `lastContacted` to storage
2. Add tests for valid and invalid `birthday` and `lastContacted` inputs

Add birthday

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/ViewPolicyCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/policy/DeletePolicyCommandParser.java
src/main/java/seedu/address/model/client/Client.java
src/main/java/seedu/address/model/policy/Policy.java
src/main/java/seedu/address/model/policy/exceptions/InvalidPolicyIndexException.java
src/main/java/seedu/address/storage/JsonAdaptedClient.java
src/main/java/seedu/address/ui/ClientCard.java
src/test/java/seedu/address/logic/LogicManagerTest.java

Add DeletePolicy command

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/policy/AddPolicyCommandParser.java
src/main/java/seedu/address/logic/parser/policy/DeletePolicyCommandParser.java
src/main/java/seedu/address/logic/parser/policy/EditPolicyCommandParser.java
src/main/java/seedu/address/storage/JsonAdaptedPolicy.java

Issue#91 update policy

---

src/main/java/seedu/address/logic/commands/ContactedCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ContactedCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/model/client/DateTime.java

Add `ContactedCommand`

---

docs/DeveloperGuide.md

Update Developer Guide to describe Client features

Update Client features in Developer Guide

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/meeting/AddMeetingCommand.java
src/main/java/seedu/address/logic/commands/meeting/DeleteMeetingCommand.java
src/main/java/seedu/address/logic/commands/meeting/EditMeetingCommand.java
src/main/java/seedu/address/logic/commands/meeting/ListMeetingCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/meeting/ListMeetingCommandParser.java

135 meetings filter

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/SortCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Add SortCommand

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/client/Date.java
src/main/java/seedu/address/model/client/DateTime.java
src/main/java/seedu/address/storage/JsonAdaptedClient.java

Fix loading `birthday` or `lastContacted`

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/meeting/ListMeetingCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/meeting/AddMeetingCommandParser.java
src/main/java/seedu/address/logic/parser/meeting/ListMeetingCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/meeting/Meeting.java
src/main/java/seedu/address/model/meeting/NonOverlappingMeetingList.java

Add option to view upcoming meetings or all meetings and change sort direction

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/storage/JsonAdaptedClient.java
src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
src/test/data/JsonSerializableAddressBookTest/overlappingMeetingsAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalMeetingsAddressBook.json

Add `birthday` and `lastContacted` as optional parameters to the `addClient` command

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ViewClientCommand.java
src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/client/Client.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Fix client view not updating on edit after sort

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
src/main/java/seedu/address/model/client/Client.java
src/main/java/seedu/address/model/policy/UniquePolicyList.java
src/main/java/seedu/address/model/policy/exceptions/EmptyPolicyListException.java
src/main/java/seedu/address/model/policy/exceptions/PolicyNotEditedException.java

195 editpolicy wrong example

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/meeting/CloseMeetingCommand.java
src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/client/Client.java
src/main/java/seedu/address/model/policy/UniquePolicyList.java
src/main/java/seedu/address/model/policy/exceptions/EmptyPolicyListException.java
src/main/java/seedu/address/model/policy/exceptions/PolicyNotEditedException.java

198 delete client meetings bug

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/SortCommandParser.java

Update ug for sort

---

docs/UserGuide.md

[PE-D] Fix user guide

---

src/main/java/seedu/address/ui/MainWindow.java

Closes #182.
Close tutorial window if open on exit.

Fix exit not closing tutorial window

---

src/main/resources/view/ClientDisplayPanel.fxml

Fixes #179.
Right panel not resizing on window resize.
Remove AnchorPane nesting.

Fix right panel not resizing

---

src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/ui/MainWindow.java

Fixes #174.
Client view remains in right panel after deleting that particular client.

Fix client view remaining after delete

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java

187: Fix bug where empty note can be used for addNote

---

docs/UserGuide.md
src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java

189 bug documentation addnote

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
src/main/java/seedu/address/logic/parser/ContactedCommandParser.java

224 bug future lastcontacted

---

docs/UserGuide.md
src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/commands/ViewClientCommand.java
src/test/java/seedu/address/logic/LogicManagerTest.java

Empty client list bugs

---

docs/DeveloperGuide.md
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java

fix clear bug when client is displayed

---

src/main/java/seedu/address/logic/commands/meeting/DeleteMeetingCommand.java
src/main/java/seedu/address/model/meeting/NonOverlappingMeetingList.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/meeting/AddMeetingCommandTest.java
src/test/java/seedu/address/logic/commands/meeting/DeleteMeetingCommandTest.java
src/test/java/seedu/address/logic/commands/meeting/ListMeetingCommandTest.java
src/test/java/seedu/address/model/meeting/MeetingTest.java
src/test/java/seedu/address/model/meeting/NonOverlappingMeetingTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/TypicalMeetings.java

Write tests for meeting-related code

---

src/main/java/seedu/address/logic/commands/meeting/CloseMeetingCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/meeting/Meeting.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/meeting/AddMeetingCommandTest.java
src/test/java/seedu/address/logic/commands/meeting/CloseMeetingCommandTest.java
src/test/java/seedu/address/logic/parser/meeting/CloseMeetingCommandParserTest.java
src/test/java/seedu/address/testutil/TypicalMeetings.java

add tests for close meeting

---

src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
src/main/java/seedu/address/model/policy/UniquePolicyList.java
src/test/java/seedu/address/logic/commands/policy/AddPolicyCommandTest.java
src/test/java/seedu/address/logic/commands/policy/DeletePolicyCommandTest.java
src/test/java/seedu/address/logic/commands/policy/EditPolicyCommandTest.java
src/test/java/seedu/address/model/policy/UniquePolicyListTest.java
src/test/java/seedu/address/testutil/TypicalClients.java

- [] add test cases for policy command parsers
- [] add test cases for policy utils

add test cases for policy commands
